# Generated by Django 6.0.1 on 2026-02-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
